# Generated by Django 6.0.3 on 2026-07-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="semester",
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="semester",
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="pyq",
            name="semester",
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="syllabus",
            name="semester",
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
    ]
