# Generated by Django 6.0.3 on 2026-07-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_note_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="pyq",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
