# Generated by Django 6.0.3 on 2026-07-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_pyq_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pyq",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
